server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:      #路由
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #需要注意的是uri的协议为lb，表示启用Gateway的负载均衡功能
          predicates:  #断言
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
            #- After=2020-04-14T16:21:48.539+08:00[Asia/Shanghai] #此时间以后，方法才启用
            #- Cookie=username,atguigu    #并且Cookie是username=atguigu才能访问
            #- Header=X-Request-Id, \d+  #请求头中要有X-Request-Id属性并且值为整数的正则表达式
        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
            - Cookie=username,atguigu #curl http://localhost:9527/payment/lb --cookie "username=atguigu"


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


